//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.shot4Client = new HashSet<shot4Client>();
        }
        public Client(string tz, string firstName, string lastName, string postalCode, DateTime birthDate, string telephone, string selphone, DateTime beIllDate,
             DateTime beHealthDate, string city, string street, string numB)
        {
            this.tz = tz;
            this.firstName = firstName;
            this.lastName = lastName;
            this.postalCode = postalCode;
            this.birthDate = birthDate;
            this.telephone = telephone;
            this.selphone = selphone;
            this.beIllDate = beIllDate;
            this.beHealthDate = beHealthDate;
            this.T_Address.city = city;
            this.T_Address.street = street;
            this.T_Address.numBuild = numB;
        }





        public string tz { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string postalCode { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string telephone { get; set; }
        public string selphone { get; set; }
        public Nullable<System.DateTime> beIllDate { get; set; }
        public Nullable<System.DateTime> beHealthDate { get; set; }

        public virtual T_Address T_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shot4Client> shot4Client { get; set; }
    }
}
