//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class shot4Client
    {
        public int Id_shot4Client { get; set; }
        public string tz { get; set; }
        public Nullable<int> codeShot { get; set; }
        public Nullable<System.DateTime> shotDate { get; set; }
    
        public virtual Shot Shot { get; set; }
        public virtual Person Person { get; set; }
    }
}
