//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Address
    {
        public string postalCode { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string numBuild { get; set; }
        public string tz { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
